### ISSUE TITLE
how i can use two time within same page 

### ISSUE THREAD

**Issue by khushmohammad** [masroorejaz/react-simple-captcha#20]
i am not able to use my component two time within same page

**Comment by masroorejaz** [comment]
I wrote a work around for you since it's only support one Captcha par Page.

Main Page
[captcha_test.zip](https://github.com/masroorejaz/react-simple-captcha/files/8934959/captcha_test.zip)
Changes You have to made in node modules of react-simple-captcha file. You also need to publish it as npm otherwise these changes will be overwrite.
[react-simple-captcha.zip](https://github.com/masroorejaz/react-simple-captcha/files/8934962/react-simple-captcha.zip)

Kindly let me know if you still have any further issue.

Thank you.

**Comment by khushmohammad** [comment]
thanks

**Comment by Gourishmesta** [comment]
@masroorejaz 
Why cant we pass a id as props to LoadCanvasTemplate_HTML and LoadCanvasTemplateNoReload_HTML instead of creating a separate method loadCaptchaEnginge2, LoadCanvasTemplate2 etc.
if we pass a different id we can use as many captcha engine on single page

will this be possible?

Sorry if i sound crazy!!

Thank you
